### ISSUE TITLE
GP model, Combination of individual responses into a single broadband

### ISSUE THREAD

**Issue by DiegoRenato** [SCECcode/bbp#47]
Hello, I have a strong question about the Graves and Pitarka model (GP). How made the combination  between  the individual low- and high-frequency responses into a single broadband time series using a set of matched fourth order Butterworth filters having a common corner frequency of 1 Hz? Please can you share the formulations?

Thanks

**Comment by fabiolsilva** [comment]
Hi,

According to Rob Graves, the basic process consists of:

1) Apply Nth-order, zero-phase butterworth filter with lowpass corner at 1 Hz to the “low frequency” (deterministic) time series.

2) Apply Nth-order, zero-phase butterworth filter with highpass corner at 1 Hz to the “high frequency” (stochastic) time series.

3) Sum the two filtered time series together to obtain the broadband result.

 The butterworth filters described above are “matched” in the sense that their Fourier amplitude spectra sum to unity for all frequencies.

The GP approach on the Broadband Platform is implemented in the match.py code (using method 2 as specified in match_cfg.py, see also match.py lines 95-104, in order to better account for the mismatch in phase between the deterministic and stochastic motions.)

**Comment by DiegoRenato** [comment]
Thank you...!

**Comment by 397832348** [comment]
Hello, I have a strong question about the Graves and Pitarka model (GP)，too.I want to use GP15.6 model （slip distributions generated using the wavenumber filtering approach with random phasing），However, I couldn't find the specific location of this part of the program in BBP. Could you please help me to pinpoint the exact location of this code? This is very important to me. Thank you very much.
